spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/english_learning"
    username: postgres
    password: postgres

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update  # ??? validate / none / create / create-drop
    show-sql: true

  application:
    name: english_learning
